### ISSUE TITLE
IPDK tutorial on Fedora 33 baremetal

### ISSUE THREAD

**Issue by dhanyarpillai** [ipdk-io/ipdk#3] opened 2021-11-01 11:57 UTC
I  have P4-OVS and p4-sde all built successfully on Fedora 33 host.
But an error occurs with gnmi-cli for interface creation. "Return grpc errno (14), Reason: Connect Failed"

Any pointers?

**Comment by stolsma** [comment] 2021-11-01 20:36
Quick check: did you open tcp port 9339 (of gNMI) on the host firewall?

**Comment by vsureshkumarp** [comment] 2021-11-02 04:29
Assuming you started P4 OvS and no issues observed for OvS bringup. 
Are you trying the gnmi-cli command using **sudo** command?
If you are not using with **sudo**, please try the same. 

If you see the same issue even with the **sudo** command, please paste the following commands output
     1. **ps -aef | grep ovs**
     2. **netstat -anpt | grep ovs**

**Comment by dhanyarpillai** [comment] 2021-11-02 09:12
This is fixed now. Setting no_proxy for grpc server helped.

Would be good to capture this in the Readme as well.

**Comment by vsureshkumarp** [comment] 2021-11-02 17:59
Thanks @dhanyarpillai for the update. 
Actually we haven't really seen a single instance of this error earlier either in Bare Metal or container environments.
Spent some time to analyze the root cause of the issue.
**Here are couple of observations:**
1. It is working without any issues when ENV NO_PROXY is not set at all.
2. If we set ENV NO_PROXY then we need to make sure “0.0.0.0” is also part of the list.
    Ex: NO_PROXY=localhost,127.0.0.1,0.0.0.0,localaddress....

**Following changes are required to address this kind of issues in future**
1. Existing gnmi-cli utility connecting 0.0.0.0:9339. Better to modify for now to connect on localhost i.e. 127.0.0.1
2. Updating README to provide instructions on configuring NO_PROXY settings.

We will take care of above changes in next PR.

**Comment by vsureshkumarp** [comment] 2021-11-04 06:25
All above listed changes committed.

**Closed by vsureshkumarp** 2021-11-04 06:25 UTC
